id: P008015
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4853
  title: བོད་ཀྱི་དགོན་སྡེ་ཁག་གཅིག་གི་ངོ་སྤྲོད་མདོར་བསྡུས་
  author: ''
  volumes:
    cc1c09f7aef4470c94e512d3df198717:
      image_group_id: I1KG5938
      title: ''
      volume_number: 1
      total_pages: 242
ebook_metadata:
  title: བོད་ཀྱི་དགོན་སྡེ་ཁག་གཅིག་གི་ངོ་སྤྲོད་མདོར་བསྡུས་
  author: ''
  sku: P008015
  cover: cover.jpg
  layers:
  - pagination
